find_path(FREEIMAGE_INCLUDE_DIR FreeImage.h ${CMAKE_SOURCE_DIR}/dependence/FreeImage/Dist/x32)
find_library(FREEIMAGE_LIBRARY NAMES FreeImage PATHS ${CMAKE_SOURCE_DIR}/dependence/FreeImage/Dist/x32)

IF(FREEIMAGE_INCLUDE_DIR AND FREEIMAGE_LIBRARY)
	SET(FREEIMAGE_FOUND TRUE)
ENDIF()